[package]
name = "deadcell-solar-conquest-server"
version = "0.6.1"
authors = ["Skippy <steelstone3@gmail.com>", "Demengies <Demengies@gmail.com>"]
edition = "2024"
homepage = "https://github.com/Steelstone3/Deadcell-Solar-Conquest"
repository = "https://github.com/Steelstone3/Deadcell-Solar-Conquest"
license = "GPLv3"
readme = "README.md"
include = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.19", features = ["serialize"] }
bevy_renet = { version = "5" }
bevy_replicon = "0.42"
bincode-next = { version = "3", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
rand = "0.10.2"
reedline = "0.50.0"

# Ctrl-C handler for graceful shutdown
ctrlc = "3"

# Logging support for routing Bevy logs to stderr
tracing-subscriber = "0.3"
once_cell = "1.20"
chrono = "0.4"
crossbeam = "0.8"
tracing = "0.1"

# Latest and greatest dependencies
rand_derive2 = "0"
float-lerp = "0"
rayon = "1"

[dev-dependencies]
renet_visualizer = "3"
rstest = "0"

# No optimisation for better debugging. Set to 1 for some optimisation
[profile.dev]
opt-level = 0

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
