[package]
name = "deadcell-solar-conquest-shared"
version = "0.6.1"
authors = ["Skippy <steelstone3@gmail.com>", "Demengies <Demengies@gmail.com>"]
edition = "2024"
homepage = "https://github.com/Steelstone3/Deadcell-Solar-Conquest"
repository = "https://github.com/Steelstone3/Deadcell-Solar-Conquest"
license = "GPLv3"
readme = "README.md"
include = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Fixed version dependencies
bevy = { version = "0.19", features = ["serialize"] }
bevy_renet = "5"
serde = { version = "1", features = ["derive"] }
rand = "0.8"

# Latest and greatest dependencies
rand_derive2 = "0"

# No optimisation for better debugging. Set to 1 for some optimisation
[profile.dev]
opt-level = 0

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
